#!/bin/bash
set -e

# Load GitHub credentials
source $(pwd)/.secrets

echo $GITHUB_USER
echo $GITHUB_TOKEN

cabal v2-run nix-package-versions-exe -- \
  update \
  --from  2023-01-01 \
  --until 2023-02-01 \
  --github-user  $GITHUB_USER \
  --github-token $GITHUB_TOKEN \
  --db-root database \
  +RTS -N


