name: main

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

run-name: ${{ github.workflow }} | ${{ github.event.pull_request.number }} ${{ github.event.pull_request.title || github.event.head_commit.message }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: docker build --tag lazamar/nix-package-versions:latest .
      working-directory: ./

    - name: Test
      run: docker run lazamar/nix-package-versions:latest ./utils.sh test

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Upload to Docker Hub
      if: github.ref_name == 'main'
      run: docker push lazamar/nix-package-versions:latest
